apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: hohnbot
    provider: github
    repository: temp2
  name: hohnbot-temp2
spec:
  description: Imported application for hohnbot/temp2
  httpCloneURL: https://github.com/hohnbot/temp2.git
  org: hohnbot
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: temp2
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/hohnbot/temp2.git
