adminUser:
  password: local:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: alanhohn@gmail.com
  token: local:jenkinsx/pipelineUser:token
  username: hohnbot
prow:
  hmacToken: local:jenkinsx/prow:hmacToken
